### ISSUE TITLE
PyTorch Geometric Temporal

### ISSUE THREAD

**Issue by benedekrozemberczki** [AndersonMonken/AINET-GNN-Trade21#1]
Hi there,

Did the PyTorch Geometric Temporal models work out for you?

Bests,

Benedek

**Comment by AndersonMonken** [comment]
Hi!

Sorry for the delaying in seeing this. Yes, the PyTorch Geometric Temporal models do work well. The example code on the package site can be confusing. I found a few github repos that use the package and was able to gain some insight on usage from that. Happy to talk more about it if you need pointers.

**Comment by AndersonMonken** [comment]
Hi Benedek,

Sorry for missing this comment earlier. The models did work out well for us! The documentation to build the temporal layer was easy to follow. I struggled a bit with how to send the temporal data through the layer, but figured it out after finding other repos using the package.

Thanks for reaching out,
Anderson
